# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b1080f5150d200c13920aaed9e15e32ecd3fe665696718621455acfcf06088be91ca5085f9c5a7e37389626a1c9107207b1e0b990fe09b471b9c321c041e7eb3

test:
  secret_key_base: 95b1a87e32442056c90bb3be10a8cdf58ac5a52c6442d955691edec274df6aaef8061f9c5b6b3ca1dbc7df00279e96b039451f1ff25fa6cc2e54fbdffe041692

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
